### ISSUE TITLE
emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack'

### ISSUE THREAD

**Issue by pjuanda** [shinsaka/fluent-plugin-elb-log#37]
Hi,

I just encounter this issue
`#0 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-01 02:35:16 UTC:Time" location="/var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:61:in `write'"`

This is the full stack trace of the error:
```
fluentd    | 2018-08-30 04:41:38 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-01 02:35:16 UTC:Time" location="/var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:61:in `write'" tag="elb_access_log"
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:61:in `write'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:61:in `block in to_msgpack_stream'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:193:in `block in each'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:192:in `each'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:192:in `each'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event.rb:60:in `to_msgpack_stream'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/output.rb:904:in `block in <class:Output>'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/buffer.rb:566:in `block in write_once'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/buffer.rb:557:in `write_once'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/buffer.rb:282:in `block in write'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/buffer.rb:280:in `each'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/buffer.rb:280:in `write'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/output.rb:981:in `block in handle_stream_simple'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/output.rb:865:in `write_guard'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/output.rb:980:in `handle_stream_simple'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/output.rb:855:in `execute_chunking'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin/output.rb:778:in `emit_buffered'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event_router.rb:159:in `emit_events'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event_router.rb:96:in `emit_stream'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/event_router.rb:87:in `emit'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:289:in `block (2 levels) in emit_lines_from_buffer_file'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:282:in `each_line'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:282:in `block in emit_lines_from_buffer_file'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:281:in `open'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:281:in `emit_lines_from_buffer_file'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:154:in `block in input'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:138:in `each'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elb-log-0.9.0/lib/fluent/plugin/in_elb_log.rb:138:in `input'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
fluentd    |   2018-08-30 04:41:38 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'cd
```
AFAIK, `RubyTime` object can't immediately packed into `msgpack`, instead you have to convert it to string first, before you can pack it into `msgpack` binary

```
# this will error:
x = { a: Time.now }.to_msgpack

# this will ok:
x = { a: Time.now }.to_s.to_msgpack
```

In https://github.com/shinsaka/fluent-plugin-elb-log/blob/master/lib/fluent/plugin/in_elb_log.rb#L289, i see that it use `Time.parse(line_match[:time])` and when i check your other library https://github.com/shinsaka/fluent-plugin-rds-pgsql-log/blob/master/lib/fluent/plugin/in_rds_pgsql_log.rb#L193, you use `Fluent::Engine.now` .

I've tried overwrite your `in_elb_log.rb` and replace `Time.parse(...)` with `Fluent::Engine.now` - and *it works*.

**Comment by GabrielCastro** [comment]
Looks like it was introduced here: https://github.com/shinsaka/fluent-plugin-elb-log/commit/45c413dd8b78d5f0516529fbeffa6b8b44b55aaa#diff-8685ad23c90574e620fcd1778e857c28 

for the time being using version `0.8.0` still works
